{
 "title": "Information System - Team 10 - ECE NTUA 2022-2023",
 "time": { "from": "2024-11-05T00:00:00.000Z", "to": "2024-11-23T00:00:00.000Z" },
 "panels": [
  {
   "title": "Th1,Th2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "aggregator": "none", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "avgTh1" },
    { "aggregator": "sum", "downsampleAggregator": "last", "downsampleFillPolicy": "none", "metric": "avgTh2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "th1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "th2" }
   ]
  },
  {
   "title": "Th1, Th2",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 0 },
   "targets": [
    { "aggregator": "none", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "avgTh1" },
    { "aggregator": "sum", "downsampleAggregator": "last", "downsampleFillPolicy": "none", "metric": "avgTh2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "th1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "th2" }
   ]
  },
  {
   "title": "Hvac1,2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    { "aggregator": "none", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "hvac1" },
    { "aggregator": "sum", "downsampleAggregator": "last", "downsampleFillPolicy": "none", "metric": "hvac2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumHvac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumHvac2" }
   ]
  },
  {
   "title": "Mean Hvac1,2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "aggregator": "none", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "hvac1" },
    { "aggregator": "sum", "downsampleAggregator": "last", "downsampleFillPolicy": "none", "metric": "hvac2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumHvac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumHvac2" }
   ]
  },
  {
   "title": "Miac1,2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "miac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "miac2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMiac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMiac2" }
   ]
  },
  {
   "title": "Miac1,2",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 20 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "miac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "miac2" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMiac1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMiac2" }
   ]
  },
  {
   "title": "Wtot",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "wtot" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "maxWtot" }
   ]
  },
  {
   "title": "Avg Wtot",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "wtot" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "maxWtot" }
   ]
  },
  {
   "title": "Etot",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 40 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "etot" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "maxEtot" }
   ]
  },
  {
   "title": "Mean values of Etot",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "etot" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "maxEtot" }
   ]
  },
  {
   "title": "W1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "w1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumW1" }
   ]
  },
  {
   "title": "Most recent values of W1/sumW1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "w1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumW1" }
   ]
  },
  {
   "title": "Mov1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 54 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mov1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMov1" }
   ]
  },
  {
   "title": "StdDev of Mov1",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mov1" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "sumMov1" }
   ]
  },
  {
   "title": "tenDaysLateStreamW1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 64 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "tenDaysLateStreamW1" }
   ]
  },
  {
   "title": "tentenDaysLateStream",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 64 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "tenDaysLateStreamW1" }
   ]
  }
 ]
}